### ISSUE TITLE
講義の日程調整

### ISSUE THREAD

**Issue by mugifly** [odentools/interactive-comm-book#3]
https://github.com/odentools/odentools/issues/1 のとおり，
2016年度のスタディスキルにおいて広報活動をさせていただけることとなりました．

ついては，Webの世界への入門として楽しんでいただける授業資料を検討し，本リポジトリで作成を行います．

以下の項目について調整および確認をお願いします．
- 日程
- 確保可能な時間　(15分くらいほしい...無理か...．)
- PC持参の有無 ＆ インターネット接続が可能か
- 座席表 (座席指定であるかどうか)

**Comment by d-yano** [comment]
日程：４月１８日（月）
確保可能な時間：１０分程度
PCの時間の有無：可能
インターネット接続可能かどうか：授業前等，事前に接続が必要かと思います．
ちなみに，Tでは前期月曜３時間目の授業は無いので，もしかしたら１つ前のコマは教室が開いているかも．．．
座席表 ：slackに投稿しました．
